name: NPM Publish

on:
  release:
    types:
      - published

jobs:
  publish-to-npm:
    permissions:
      contents: read
      id-token: write
    uses: bloq/actions/.github/workflows/npm-publish.yml@v1
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
